metadata:
  author: "REANA Developers."
  title: "Reusable analysis example - ROOT6 and RooFit"
code:
  files:
    - gendata.C
    - fitdata.C
environment:
  - type: docker
    image: reanahub/reana-env-root6
workflow:
  type: yadage
  file: workflow.yml
parameters:
  events: 20000
output:
  files:
    - plot.png
