notifications:
  email: false

sudo: true

language: python

cache:
  - pip

python:
  - 2.7

services:
  - docker

before_install:
  - travis_retry pip install yadage

script:
  - yadage-validate workflow/yadage/workflow.yaml | grep -q 'workflow validates'
  - docker run -i -t  --rm -v `pwd`:/workdir reanahub/reana-env-root6 bash -c "
      cd /workdir &&
      mkdir -p ./results &&
      root -b -q './code/gendata.C(20000,\"./results/data.root\")'"
  - ls -l `pwd`/results/data.root
  - docker run -i -t  --rm -v `pwd`:/workdir reanahub/reana-env-root6 bash -c "
       cd /workdir &&
       root -b -q './code/fitdata.C(\"./results/data.root\",\"./results/plot.png\")'"
  - ls -l `pwd`/results/plot.png
