# This file is part of REANA.
# Copyright (C) 2020 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install yadage

      - name: Validate workflow
        run: yadage-validate workflow/yadage/workflow.yaml | grep -q 'workflow validates'

      - run: docker run -i --rm -v `pwd`:/workdir reanahub/reana-env-root6 bash -c "
              cd /workdir &&
              mkdir -p ./results &&
              root -b -q './code/gendata.C(20000,\"./results/data.root\")'"

      - run: ls -l `pwd`/results/data.root

      - run: docker run -i --rm -v `pwd`:/workdir reanahub/reana-env-root6 bash -c "
              cd /workdir &&
              root -b -q './code/fitdata.C(\"./results/data.root\",\"./results/plot.png\")'"

      - run: ls -l `pwd`/results/plot.png
